### ISSUE TITLE
Can React Native or iOS Native Applications use hapijs/iron for user auth?

### ISSUE THREAD

**Issue by mehranhydary** [hapijs/iron#100]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes - need to decide if i should use iron or jwt for user auth because right now i am creating a web app but later might also create a react native app
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v14.18.0
* *module version*: latest
* *environment* (e.g. node, browser, native): node, browser, native
* *used with* (e.g. hapi application, another framework, standalone, ...): react native or iOS native
* *any other relevant information*: i want to create a native mobile application and I am wondering if i can use iron for auth

#### How can we help?

Can React Native or iOS Native Applications use hapijs/iron for user auth?

```js
// n/a
```

**Comment by kanongil** [comment]
No, iron does not do user auth and is designed to work at the provider end. It’s used to create a token that could potentially be used to represent a user once signed in through whatever mechanism. Unless you plan to do p2p communication, it should never be used on the client.
